# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('search_key', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('login', models.CharField(blank=True, max_length=254, null=True)),
                ('user_id', models.FloatField()),
                ('gravatar_id', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=254)),
                ('html_url', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('followers_url', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('following_url', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('gists_url', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('starred_url', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('subscriptions_url', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('organizations_url', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('repos_url', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('events_url', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('received_events_url', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('score', models.FloatField()),
                ('picture', models.CharField(blank=True, max_length=508, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
